### ISSUE TITLE
anime and manga commands not working

### ISSUE THREAD

**Issue by mapuya19** [AlexanderColen/Annie-May-Discord-Bot#101]
It seems as though certain commands, such as `-anime` and `-manga` are not currently working, but `-search` does, as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/15944396/126726058-679f70fb-17e4-4a39-8fba-f21a16ace1b7.png)

**Comment by AlexanderColen** [comment]
Will investigate this later today after work

Update: Turns out that my docker installation got undone on the VPS (_again_) so the database was offline. Working on getting it back up and running.

**Comment by AlexanderColen** [comment]
Got her back up and running, had some outage with the database however so I lost the data from may 30th and onwards. 😢

**Comment by mapuya19** [comment]
@AlexanderColen 

Looks like it broke the same way again, any ideas on when it'll be fixed?
