### ISSUE TITLE
User command not loading

### ISSUE THREAD

**Issue by Yakiyo** [AlexanderColen/Annie-May-Discord-Bot#103]
after the new slash command update, i (and a few other members ) were trying the commands. the `/user` command didnt work. It doesnt work if i provide a username in the option, or even when i dont specify a username.

Here's a screenshot
![image](https://user-images.githubusercontent.com/91675932/191474356-811eaa83-3779-4dde-a7e2-6dc34a85a1d4.png)

**Comment by purpleblueslime** [comment]
same w `/affinity`

![image](https://user-images.githubusercontent.com/84064124/192078228-218aa8ce-1266-4383-a5a2-b794634ed54c.png)

**Comment by AlexanderColen** [comment]
Thanks for notifying me of this. I will look into this when I have some more spare time.

Could either of you @Yakiyo @purpleblueslime tell me if this happened to be in guilds with a lot of members?

**Comment by purpleblueslime** [comment]
Alright here it goes!
I tried using `/affinity`, `/user` in my test server which has only <b>12 users</b>,
also tried it in my server with <b>58 users</b>,
and a friend's server with <b>132 users</b>.

<details>
<summary>Screen shots~</summary>
<img src='https://user-images.githubusercontent.com/84064124/192498896-fce70a68-c3bb-42de-ae99-a1d9cafc5c9f.png'/> <img src='https://user-images.githubusercontent.com/84064124/192501892-7f3ad013-1077-4fc4-8dad-a49010f58e1a.png' />
</details>

Broken in all of em.

Doesn't look like it's a server thing, cause `/user` is also broken. I don't think it relies on fellow server mems.

**Comment by TenTraicion** [comment]
It's still broken ....

**Comment by AlexanderColen** [comment]
@Yakiyo @TenTraicion  I know this is literally overa year late (Life sure is something...)

But this should now be resolved with the latest build.
