### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Kyerstorm** [AlexanderColen/Annie-May-Discord-Bot#106]
There r multiple errors recently such as:
Incorrectly showing how many users have read/watched smth by not showing them
Commands such as /affinity not working 
/manga and /anime taking a very long time to load and sometimes fail

**Comment by AlexanderColen** [comment]
@Kyerstorm I know this is literally nearly a year late (Life sure is something...)

But this should now be resolved with the latest build.
