### ISSUE TITLE
Unable to add to new servers

### ISSUE THREAD

**Issue by mapuya19** [AlexanderColen/Annie-May-Discord-Bot#93]
When adding to new servers, this message pops up:

![image](https://user-images.githubusercontent.com/15944396/108322782-e15c8400-7193-11eb-8968-2aa3f2cf3c93.png)

Here's the [link mentioned](https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting).

**Comment by AlexanderColen** [comment]
Ah thank you for bringing this to my attention, I completely forgot to finish the verification earlier.

I started the verification proces now and will update when I hear back from Discord.

**Comment by AlexanderColen** [comment]
First part of the verification is done, now it's up to Discord to verify it! 🤞 
![image](https://user-images.githubusercontent.com/25740945/108353604-58a30f80-71b6-11eb-9c04-b0a88023c7de.png)

**Comment by AlexanderColen** [comment]
Annie got verified as of yesterday, so she can be added to servers again. 👍
