### ISSUE TITLE
Use mean score instead of count when determining tendencies.

### ISSUE THREAD

**Issue by AlexanderColen** [AlexanderColen/Annie-May-Discord-Bot#94]
Score will actually show taste, whereas count will just show the most & least common genres.

**Comment by oridistor** [comment]
Hi, can I offer an idea? I think I might actually try to implement it and send you a pr.

I think about maybe making this configurable with the guild setup, so you can decide how you want to rank things in your server.

There will be 4 possible metrics:
1. count (as it is right now)
2. mean_score (like I offered originally)
3. total time watched (another sortable metric that anilist offers)
4. Weighted mean_score.

Weighted mean score will be marked for being experimental and a bit more process heavy, and will calculate for each item the score personally by weighing in the numbers of the item to a certain level, according to how many items you watched.

Like I mentioned, I have no problem with implementing such an algorithm or even trying to do the "configurable weighting"

**Comment by AlexanderColen** [comment]
The weighted mean score actually sounds like the best idea if it is implemented properly.

Feel free to shoot in a PR for the weighted mean_score, for now I will change the default to mean_score and look into making it customizable per server.

**Comment by AlexanderColen** [comment]
> 
> 
> Hi, can I offer an idea? I think I might actually try to implement it and send you a pr.
> 
> I think about maybe making this configurable with the guild setup, so you can decide how you want to rank things in your server.
> 
> There will be 4 possible metrics:
> 
>     1. count (as it is right now)
> 
>     2. mean_score (like I offered originally)
> 
>     3. total time watched (another sortable metric that anilist offers)
> 
>     4. Weighted mean_score.
> 
> 
> Weighted mean score will be marked for being experimental and a bit more process heavy, and will calculate for each item the score personally by weighing in the numbers of the item to a certain level, according to how many items you watched.
> 
> Like I mentioned, I have no problem with implementing such an algorithm or even trying to do the "configurable weighting"

Instead of keeping track of it in here, I made a separate issue for it. (#98) Please redirect the updates on potential PR progress there.

I changed it to use meanScore by default for now and added some extra tendencies to look at minutesWatched and chaptersRead as well.
